//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class AccessKeyManagement
    {
        public int AccessKeyID { get; set; }
        public string Key { get; set; }
        public string EmailUser { get; set; }
        public string EmailAdmin { get; set; }
        public bool Active { get; set; }
    }
    
}
