//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Appointment
    {
        public Appointment()
        {
            this.AppointmentLogs = new HashSet<AppointmentLog>();
            this.AppointmentNotifies = new HashSet<AppointmentNotify>();
            this.AppointmentParticipants = new HashSet<AppointmentParticipant>();
            this.UserPackagePurchaseHistories = new HashSet<UserPackagePurchaseHistory>();
            this.GiftCardHistories = new HashSet<GiftCardHistory>();
            this.KuyamEvents = new HashSet<KuyamEvent>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int AppointmentID { get; set; }
        public Nullable<int> ServiceCompanyID { get; set; }
        public int AppointmentStatusID { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public string Title { get; set; }
        public Nullable<int> ContactType { get; set; }
        public string ContactPerson { get; set; }
        public bool AllDay { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Url { get; set; }
        public int PersonCount { get; set; }
        public string Desc { get; set; }
        public string Notes { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int CustID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PreapprovalKey { get; set; }
        public string SenderEmail { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> AttendeesNumber { get; set; }
        public Nullable<bool> IsViewDetail { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public string EmployeeName { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> BookingType { get; set; }
        public Nullable<int> ClassSchedulerID { get; set; }
    
        public virtual CompanyEmployee CompanyEmployee { get; set; }
        public virtual Cust Cust { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual HotelStaff HotelStaff { get; set; }
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual ServiceCompany ServiceCompany { get; set; }
        public virtual ICollection<AppointmentLog> AppointmentLogs { get; set; }
        public virtual ICollection<AppointmentNotify> AppointmentNotifies { get; set; }
        public virtual ICollection<AppointmentParticipant> AppointmentParticipants { get; set; }
        public virtual ICollection<UserPackagePurchaseHistory> UserPackagePurchaseHistories { get; set; }
        public virtual ICollection<GiftCardHistory> GiftCardHistories { get; set; }
        public virtual ICollection<KuyamEvent> KuyamEvents { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
    
}
