//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class AppointmentNotify
    {
        public int NotifyId { get; set; }
        public int AppointmentId { get; set; }
        public int NotifyType { get; set; }
        public string Message { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime DateSent { get; set; }
        public int CustId { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> StaffID { get; set; }
    
        public virtual Cust Cust { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual HotelStaff HotelStaff { get; set; }
        public virtual Appointment Appointment { get; set; }
    }
    
}
