//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class AppointmentParticipant
    {
        public int AppointmentParticipantID { get; set; }
        public int AppointmentID { get; set; }
        public int CalendarID { get; set; }
        public int ParticipantStatusID { get; set; }
        public int ParticipantTypeID { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Appointment Appointment { get; set; }
    }
    
}
