//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class AppointmentLog
    {
        public int AppointmentLogID { get; set; }
        public int AppointmentID { get; set; }
        public int CustID { get; set; }
        public string Message { get; set; }
        public bool Viewed { get; set; }
        public System.DateTime LogDT { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
    
}
