//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class AppointmentTemp
    {
        public int AppointmentID { get; set; }
        public Nullable<int> ServiceCompanyID { get; set; }
        public int AppointmentStatusID { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public string Title { get; set; }
        public Nullable<int> ContactType { get; set; }
        public string ContactPerson { get; set; }
        public bool AllDay { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Url { get; set; }
        public int PersonCount { get; set; }
        public string Desc { get; set; }
        public string Notes { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int CustID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PreapprovalKey { get; set; }
        public string SenderEmail { get; set; }
        public int CalendarId { get; set; }
        public Nullable<int> AttendeesNumber { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string EmployeeName { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> ClassSchedulerID { get; set; }
    }
    
}
