//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_BlogRollItems
    {
        public int BlogRollRowId { get; set; }
        public System.Guid BlogId { get; set; }
        public System.Guid BlogRollId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string BlogUrl { get; set; }
        public string FeedUrl { get; set; }
        public string Xfn { get; set; }
        public int SortIndex { get; set; }
    }
    
}
