//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_Blogs
    {
        public int BlogRowId { get; set; }
        public System.Guid BlogId { get; set; }
        public string BlogName { get; set; }
        public string Hostname { get; set; }
        public bool IsAnyTextBeforeHostnameAccepted { get; set; }
        public string StorageContainerName { get; set; }
        public string VirtualPath { get; set; }
        public bool IsPrimary { get; set; }
        public bool IsActive { get; set; }
        public bool IsSiteAggregation { get; set; }
    }
    
}
