//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_Categories
    {
        public be_Categories()
        {
            this.CategoryFeatureds = new HashSet<CategoryFeatured>();
            this.CategoryFeaturedHotels = new HashSet<CategoryFeaturedHotel>();
        }
    
        public int CategoryRowID { get; set; }
        public System.Guid BlogID { get; set; }
        public System.Guid CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<System.Guid> FeaturedPostID { get; set; }
        public int Sequence { get; set; }
    
        public virtual ICollection<CategoryFeatured> CategoryFeatureds { get; set; }
        public virtual ICollection<CategoryFeaturedHotel> CategoryFeaturedHotels { get; set; }
    }
    
}
