//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_DataStoreSettings
    {
        public int DataStoreSettingRowId { get; set; }
        public System.Guid BlogId { get; set; }
        public string ExtensionType { get; set; }
        public string ExtensionId { get; set; }
        public string Settings { get; set; }
    }
    
}
