//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_FileStoreFileThumbs
    {
        public System.Guid thumbnailId { get; set; }
        public System.Guid FileId { get; set; }
        public int size { get; set; }
        public byte[] contents { get; set; }
    
        public virtual be_FileStoreFiles be_FileStoreFiles { get; set; }
    }
    
}
