//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_FileStoreFiles
    {
        public be_FileStoreFiles()
        {
            this.be_FileStoreFileThumbs = new HashSet<be_FileStoreFileThumbs>();
        }
    
        public System.Guid FileID { get; set; }
        public System.Guid ParentDirectoryID { get; set; }
        public string Name { get; set; }
        public string FullPath { get; set; }
        public byte[] Contents { get; set; }
        public int Size { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastAccess { get; set; }
        public System.DateTime LastModify { get; set; }
    
        public virtual be_FileStoreDirectory be_FileStoreDirectory { get; set; }
        public virtual ICollection<be_FileStoreFileThumbs> be_FileStoreFileThumbs { get; set; }
    }
    
}
