//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_FileStoreDirectory
    {
        public be_FileStoreDirectory()
        {
            this.be_FileStoreFiles = new HashSet<be_FileStoreFiles>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public System.Guid BlogID { get; set; }
        public string Name { get; set; }
        public string FullPath { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastAccess { get; set; }
        public System.DateTime LastModify { get; set; }
    
        public virtual ICollection<be_FileStoreFiles> be_FileStoreFiles { get; set; }
    }
    
}
