//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_Posts
    {
        public be_Posts()
        {
            this.Bookmarks = new HashSet<Bookmark>();
        }
    
        public int PostRowID { get; set; }
        public System.Guid BlogID { get; set; }
        public System.Guid PostID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string PostContent { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Author { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<bool> IsCommentEnabled { get; set; }
        public Nullable<int> Raters { get; set; }
        public Nullable<float> Rating { get; set; }
        public string Slug { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public string CoverPhoto { get; set; }
        public string Caption { get; set; }
        public Nullable<bool> AlowChatToBook { get; set; }
        public bool IsLocation { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Address { get; set; }
        public double Radius { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public Nullable<bool> IsEvent { get; set; }
    
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
    }
    
}
