//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_QuickNotes
    {
        public int QuickNoteID { get; set; }
        public System.Guid NoteID { get; set; }
        public System.Guid BlogID { get; set; }
        public string UserName { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
    
}
