//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_Referrers
    {
        public int ReferrerRowId { get; set; }
        public System.Guid BlogId { get; set; }
        public System.Guid ReferrerId { get; set; }
        public System.DateTime ReferralDay { get; set; }
        public string ReferrerUrl { get; set; }
        public int ReferralCount { get; set; }
        public string Url { get; set; }
        public Nullable<bool> IsSpam { get; set; }
    }
    
}
