//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class be_Users
    {
        public be_Users()
        {
            this.be_GettyImages = new HashSet<be_GettyImages>();
        }
    
        public int UserID { get; set; }
        public System.Guid BlogID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual ICollection<be_GettyImages> be_GettyImages { get; set; }
    }
    
}
