//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Bookmark
    {
        public int Id { get; set; }
        public int CustId { get; set; }
        public int PostId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual be_Posts be_Posts { get; set; }
        public virtual Cust Cust { get; set; }
    }
    
}
