//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Calendar
    {
        public Calendar()
        {
            this.AppointmentParticipants = new HashSet<AppointmentParticipant>();
            this.CalendarShares = new HashSet<CalendarShare>();
            this.RequestAppointments = new HashSet<RequestAppointment>();
            this.NonKuyamAppointments = new HashSet<NonKuyamAppointment>();
            this.ProposedAppointments = new HashSet<ProposedAppointment>();
        }
    
        public int CalendarID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public string Name { get; set; }
        public string BackColor { get; set; }
        public string ForeColor { get; set; }
        public bool IsDefault { get; set; }
        public int CalendarDisplayTypeID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string SyncCalendarId { get; set; }
    
        public virtual ICollection<AppointmentParticipant> AppointmentParticipants { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual ICollection<CalendarShare> CalendarShares { get; set; }
        public virtual ICollection<RequestAppointment> RequestAppointments { get; set; }
        public virtual ICollection<NonKuyamAppointment> NonKuyamAppointments { get; set; }
        public virtual ICollection<ProposedAppointment> ProposedAppointments { get; set; }
    }
    
}
