//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class CalendarShare
    {
        public int CalendarShareID { get; set; }
        public int CustID { get; set; }
        public int CalendarID { get; set; }
        public int ShareTypeID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Cust Cust { get; set; }
    }
    
}
