//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class CompanyEvent
    {
        public CompanyEvent()
        {
            this.CompanyServiceEvents = new HashSet<CompanyServiceEvent>();
        }
    
        public int CompanyEventID { get; set; }
        public int ProfileCompanyID { get; set; }
        public int EventID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual ICollection<CompanyServiceEvent> CompanyServiceEvents { get; set; }
    }
    
}
