//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class CompanyPackage
    {
        public CompanyPackage()
        {
            this.CompanyPackageServices = new HashSet<CompanyPackageService>();
            this.UserPackagePurchases = new HashSet<UserPackagePurchase>();
        }
    
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public string Description { get; set; }
        public int ProfileCompanyId { get; set; }
        public int PackageType { get; set; }
        public int NumberOfBooking { get; set; }
        public decimal Price { get; set; }
        public int Status { get; set; }
        public Nullable<int> DurationInMonth { get; set; }
        public string KalturaImageId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual ICollection<CompanyPackageService> CompanyPackageServices { get; set; }
        public virtual ICollection<UserPackagePurchase> UserPackagePurchases { get; set; }
    }
    
}
