//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class CompanyPackageService
    {
        public int CompanyPackageServiceId { get; set; }
        public int CompanyPackageId { get; set; }
        public int ServiceCompanyId { get; set; }
    
        public virtual CompanyPackage CompanyPackage { get; set; }
        public virtual ServiceCompany ServiceCompany { get; set; }
    }
    
}
