//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class CompanyServiceEvent
    {
        public int ID { get; set; }
        public int CompanyEventID { get; set; }
        public int ServiceCompanyID { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
    
        public virtual CompanyEvent CompanyEvent { get; set; }
        public virtual ServiceCompany ServiceCompany { get; set; }
    }
    
}
