//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class CompanyEmployee
    {
        public CompanyEmployee()
        {
            this.EmployeeServices = new HashSet<EmployeeService>();
            this.Ratings = new HashSet<Rating>();
            this.Appointments = new HashSet<Appointment>();
            this.EmployeeHours = new HashSet<EmployeeHour>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int ProfileCompanyID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public bool IsDefault { get; set; }
        public string PaymentAccount { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
    
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual ICollection<EmployeeService> EmployeeServices { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<EmployeeHour> EmployeeHours { get; set; }
    }
    
}
