//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class CompanyMedia
    {
        public int CompanyMediaID { get; set; }
        public int ProfileID { get; set; }
        public int MediaID { get; set; }
        public bool IsBanner { get; set; }
        public bool IsLogo { get; set; }
        public bool IsVideo { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<bool> IsHidden { get; set; }
    
        public virtual Medium Medium { get; set; }
        public virtual ProfileCompany ProfileCompany { get; set; }
    }
    
}
