//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class CompanyPackageImage
    {
        public int CompanyPackageImageId { get; set; }
        public int CompanyProfileId { get; set; }
        public string LocationData { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ProfileCompany ProfileCompany { get; set; }
    }
    
}
