//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Cust
    {
        public Cust()
        {
            this.AppointmentNotifies = new HashSet<AppointmentNotify>();
            this.Bookmarks = new HashSet<Bookmark>();
            this.CalendarShares = new HashSet<CalendarShare>();
            this.DiscountInvites = new HashSet<DiscountInvite>();
            this.Favorites = new HashSet<Favorite>();
            this.GettyImages = new HashSet<GettyImage>();
            this.GiftCards = new HashSet<GiftCard>();
            this.GiftCardLockCusts = new HashSet<GiftCardLockCust>();
            this.Hotels = new HashSet<Hotel>();
            this.HotelStaffs = new HashSet<HotelStaff>();
            this.Orders = new HashSet<Order>();
            this.Profiles = new HashSet<Profile>();
            this.ProposedAppointmentNotifies = new HashSet<ProposedAppointmentNotify>();
            this.Ratings = new HashSet<Rating>();
            this.RequestAppointments = new HashSet<RequestAppointment>();
            this.UserBadges = new HashSet<UserBadge>();
            this.UserDiscounts = new HashSet<UserDiscount>();
            this.HotelVisits = new HashSet<HotelVisit>();
            this.Appointments = new HashSet<Appointment>();
            this.NonKuyamAppointments = new HashSet<NonKuyamAppointment>();
            this.ProposedAppointments = new HashSet<ProposedAppointment>();
        }
    
        public int CustID { get; set; }
        public System.Guid AspUserID { get; set; }
        public int CustTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string MobileCarrier { get; set; }
        public string WorkPhone { get; set; }
        public Nullable<int> PreferredPhoneTypeID { get; set; }
        public Nullable<int> FirstAlert { get; set; }
        public Nullable<int> SecondAlert { get; set; }
        public string IcalUrl { get; set; }
        public bool EmailHtml { get; set; }
        public Nullable<int> GenderTypeID { get; set; }
        public int CustStatusTypeID { get; set; }
        public Nullable<int> CustStatusReasonTypeID { get; set; }
        public string CustStatusNote { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public System.DateTime LastVisit { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string OtherCalendar { get; set; }
        public bool OutlookCalendar { get; set; }
        public bool YahooCalendar { get; set; }
        public string TimeZoneId { get; set; }
        public int Status { get; set; }
        public string FacebookToken { get; set; }
        public string FacebookUserID { get; set; }
        public Nullable<bool> LocationReminder { get; set; }
    
        public virtual ICollection<AppointmentNotify> AppointmentNotifies { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual ICollection<CalendarShare> CalendarShares { get; set; }
        public virtual ICollection<DiscountInvite> DiscountInvites { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<GettyImage> GettyImages { get; set; }
        public virtual ICollection<GiftCard> GiftCards { get; set; }
        public virtual ICollection<GiftCardLockCust> GiftCardLockCusts { get; set; }
        public virtual ICollection<Hotel> Hotels { get; set; }
        public virtual ICollection<HotelStaff> HotelStaffs { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<ProposedAppointmentNotify> ProposedAppointmentNotifies { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<RequestAppointment> RequestAppointments { get; set; }
        public virtual ICollection<UserBadge> UserBadges { get; set; }
        public virtual ICollection<UserDiscount> UserDiscounts { get; set; }
        public virtual ICollection<HotelVisit> HotelVisits { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<NonKuyamAppointment> NonKuyamAppointments { get; set; }
        public virtual ICollection<ProposedAppointment> ProposedAppointments { get; set; }
    }
    
}
