//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class DiscountInvite
    {
        public int Id { get; set; }
        public int DiscountId { get; set; }
        public int CustId { get; set; }
        public int NumberofUsage { get; set; }
        public System.DateTime DateUsage { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Cust Cust { get; set; }
    }
    
}
