//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class DiscountRegularClient
    {
        public int DiscountRegularClientId { get; set; }
        public int DiscountId { get; set; }
        public int RegularClientId { get; set; }
        public int Status { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual RegularClient RegularClient { get; set; }
    }
    
}
