//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Discount
    {
        public Discount()
        {
            this.DiscountInvites = new HashSet<DiscountInvite>();
            this.DiscountRegularClients = new HashSet<DiscountRegularClient>();
            this.DiscountServices = new HashSet<DiscountService>();
            this.UserDiscounts = new HashSet<UserDiscount>();
        }
    
        public int DiscountId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public decimal Amount { get; set; }
        public decimal Percent { get; set; }
        public int Quantity { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool ApplyToAllServices { get; set; }
        public Nullable<int> ProfileCompanyId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int Status { get; set; }
        public int DiscountType { get; set; }
    
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual ICollection<DiscountInvite> DiscountInvites { get; set; }
        public virtual ICollection<DiscountRegularClient> DiscountRegularClients { get; set; }
        public virtual ICollection<DiscountService> DiscountServices { get; set; }
        public virtual ICollection<UserDiscount> UserDiscounts { get; set; }
    }
    
}
