//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class EmployeeHour
    {
        public int ID { get; set; }
        public System.TimeSpan FromHour { get; set; }
        public System.TimeSpan ToHour { get; set; }
        public int CompanyEmployeeID { get; set; }
        public int DayOfWeek { get; set; }
        public bool IsPreview { get; set; }
        public System.DateTime LastedUpdate { get; set; }
    
        public virtual CompanyEmployee CompanyEmployee { get; set; }

        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
    }
    
}
