//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class EmployeeService
    {
        public EmployeeService()
        {
            this.InstructorClassSchedulers = new HashSet<InstructorClassScheduler>();
        }
    
        public int ID { get; set; }
        public int ServiceCompanyID { get; set; }
        public int CompanyEmployeeID { get; set; }
    
        public virtual CompanyEmployee CompanyEmployee { get; set; }
        public virtual ServiceCompany ServiceCompany { get; set; }
        public virtual ICollection<InstructorClassScheduler> InstructorClassSchedulers { get; set; }
    }
    
}
