//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Error
    {
        public int ErrorID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Resolved { get; set; }
    }
    
}
