//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Favorite
    {
        public int FavoriteID { get; set; }
        public int CustID { get; set; }
        public int ProfileID { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual Cust Cust { get; set; }
    }
    
}
