//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class FeaturedHotel
    {
        public FeaturedHotel()
        {
            this.CategoryFeaturedHotels = new HashSet<CategoryFeaturedHotel>();
        }
    
        public int FeaturedID { get; set; }
        public int HotelID { get; set; }
        public int ProfileID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual ICollection<CategoryFeaturedHotel> CategoryFeaturedHotels { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual ProfileCompany ProfileCompany { get; set; }
    }
    
}
