//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class FeaturedCompany
    {
        public int CompanyFeaturedID { get; set; }
        public int ProfileID { get; set; }
        public System.DateTime StartDT { get; set; }
        public int priority { get; set; }
        public int FeatureType { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual ProfileCompany ProfileCompany { get; set; }
    }
    
}
