//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class GeneralTimeSlot
    {
        public int Id { get; set; }
        public System.TimeSpan FromHour { get; set; }
        public System.TimeSpan ToHour { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public int DayOfWeek { get; set; }
    
        public virtual ProfileCompany ProfileCompany { get; set; }
    }
    
}
