//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class GettyImage
    {
        public int Id { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public string GettyImageId { get; set; }
        public string Title { get; set; }
        public string UrlThumb { get; set; }
        public string UrlPreview { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PixelHeight { get; set; }
        public Nullable<int> PixelWidth { get; set; }
        public string UrlAttachment { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> CustId { get; set; }
        public string LocationData { get; set; }
    
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual Cust Cust { get; set; }
    }
    
}
