//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class GiftCardLockCust
    {
        public int Id { get; set; }
        public int CustId { get; set; }
        public System.DateTime LockedTime { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<int> FailedGiftCardAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedGiftCardAttemptStart { get; set; }
    
        public virtual Cust Cust { get; set; }
    }
    
}
