//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class GiftCard
    {
        public GiftCard()
        {
            this.GiftCardHistories = new HashSet<GiftCardHistory>();
        }
    
        public int Id { get; set; }
        public int GiftCardType { get; set; }
        public decimal Amount { get; set; }
        public bool IsActivated { get; set; }
        public string GiftCardCode { get; set; }
        public string RecipientName { get; set; }
        public string RecipientEmail { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
        public string Message { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<decimal> UsedValue { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> ShippingMethod { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public string EstimateDate { get; set; }
        public string ReceiveNumber { get; set; }
        public string TransactionID { get; set; }
        public string PayKey { get; set; }
        public int GiftStatus { get; set; }
        public int CustId { get; set; }
    
        public virtual ICollection<GiftCardHistory> GiftCardHistories { get; set; }
        public virtual Cust Cust { get; set; }
    }
    
}
