//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class GiftCardHistory
    {
        public int Id { get; set; }
        public int GiftCardId { get; set; }
        public int AppointmentId { get; set; }
        public decimal UsedValue { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual GiftCard GiftCard { get; set; }
        public virtual Appointment Appointment { get; set; }
    }
    
}
