//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Hotel
    {
        public Hotel()
        {
            this.FeaturedHotels = new HashSet<FeaturedHotel>();
            this.HotelCodes = new HashSet<HotelCode>();
            this.HotelMedias = new HashSet<HotelMedia>();
            this.HotelStaffs = new HashSet<HotelStaff>();
            this.RequestAppointments = new HashSet<RequestAppointment>();
            this.HotelVisits = new HashSet<HotelVisit>();
            this.AppointmentNotifies = new HashSet<AppointmentNotify>();
            this.ProposedAppointmentNotifies = new HashSet<ProposedAppointmentNotify>();
            this.Appointments = new HashSet<Appointment>();
            this.NonKuyamAppointments = new HashSet<NonKuyamAppointment>();
            this.ProposedAppointments = new HashSet<ProposedAppointment>();
        }
    
        public int HotelID { get; set; }
        public int CustID { get; set; }
        public Nullable<int> HotelType { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string LogoId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    
        public virtual ICollection<FeaturedHotel> FeaturedHotels { get; set; }
        public virtual ICollection<HotelCode> HotelCodes { get; set; }
        public virtual ICollection<HotelMedia> HotelMedias { get; set; }
        public virtual ICollection<HotelStaff> HotelStaffs { get; set; }
        public virtual Cust Cust { get; set; }
        public virtual ICollection<RequestAppointment> RequestAppointments { get; set; }
        public virtual ICollection<HotelVisit> HotelVisits { get; set; }
        public virtual ICollection<AppointmentNotify> AppointmentNotifies { get; set; }
        public virtual ICollection<ProposedAppointmentNotify> ProposedAppointmentNotifies { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<NonKuyamAppointment> NonKuyamAppointments { get; set; }
        public virtual ICollection<ProposedAppointment> ProposedAppointments { get; set; }
    }
    
}
