//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class HotelMedia
    {
        public int HotelMediaID { get; set; }
        public int HotelID { get; set; }
        public int MediaID { get; set; }
        public int MediaType { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Medium Medium { get; set; }
    }
    
}
