//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class HotelStaff
    {
        public HotelStaff()
        {
            this.RequestAppointments = new HashSet<RequestAppointment>();
            this.AppointmentNotifies = new HashSet<AppointmentNotify>();
            this.ProposedAppointmentNotifies = new HashSet<ProposedAppointmentNotify>();
            this.Appointments = new HashSet<Appointment>();
            this.NonKuyamAppointments = new HashSet<NonKuyamAppointment>();
            this.ProposedAppointments = new HashSet<ProposedAppointment>();
        }
    
        public int Id { get; set; }
        public int CustID { get; set; }
        public int HotelID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Cust Cust { get; set; }
        public virtual ICollection<RequestAppointment> RequestAppointments { get; set; }
        public virtual ICollection<AppointmentNotify> AppointmentNotifies { get; set; }
        public virtual ICollection<ProposedAppointmentNotify> ProposedAppointmentNotifies { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<NonKuyamAppointment> NonKuyamAppointments { get; set; }
        public virtual ICollection<ProposedAppointment> ProposedAppointments { get; set; }
    }
    
}
