//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class HotelCode
    {
        public int Id { get; set; }
        public int HotelID { get; set; }
        public string CodeNumber { get; set; }
        public Nullable<int> CodeType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
    
}
