//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class HotelVisit
    {
        public int Id { get; set; }
        public int HotelID { get; set; }
        public int CustID { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public string RoomNumber { get; set; }
    
        public virtual Cust Cust { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
    
}
