//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class ImageCrop
    {
        public ImageCrop()
        {
            this.LandingPages = new HashSet<LandingPage>();
        }
    
        public int Id { get; set; }
        public string LocationData { get; set; }
        public Nullable<int> Crop_x { get; set; }
        public Nullable<int> Crop_y { get; set; }
        public Nullable<int> Rel_width { get; set; }
        public Nullable<int> Rel_height { get; set; }
        public Nullable<int> Fr_width { get; set; }
        public Nullable<int> Fr_height { get; set; }
        public Nullable<double> ZoomPercent { get; set; }
    
        public virtual ICollection<LandingPage> LandingPages { get; set; }
    }
    
}
