//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuyam.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kuyamEntities : DbContext
    {
        public kuyamEntities()
            : base("name=kuyamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessKeyManagement> AccessKeyManagements { get; set; }
        public DbSet<AppointmentLog> AppointmentLogs { get; set; }
        public DbSet<AppointmentNotify> AppointmentNotifies { get; set; }
        public DbSet<AppointmentParticipant> AppointmentParticipants { get; set; }
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<be_BlogRollItems> be_BlogRollItems { get; set; }
        public DbSet<be_Blogs> be_Blogs { get; set; }
        public DbSet<be_Categories> be_Categories { get; set; }
        public DbSet<be_DataStoreSettings> be_DataStoreSettings { get; set; }
        public DbSet<be_FileStoreDirectory> be_FileStoreDirectory { get; set; }
        public DbSet<be_FileStoreFiles> be_FileStoreFiles { get; set; }
        public DbSet<be_FileStoreFileThumbs> be_FileStoreFileThumbs { get; set; }
        public DbSet<be_GettyImages> be_GettyImages { get; set; }
        public DbSet<be_MediaType> be_MediaType { get; set; }
        public DbSet<be_PackageFiles> be_PackageFiles { get; set; }
        public DbSet<be_Packages> be_Packages { get; set; }
        public DbSet<be_Pages> be_Pages { get; set; }
        public DbSet<be_PingService> be_PingService { get; set; }
        public DbSet<be_PostCategory> be_PostCategory { get; set; }
        public DbSet<be_PostComment> be_PostComment { get; set; }
        public DbSet<be_PostCompanies> be_PostCompanies { get; set; }
        public DbSet<be_PostMedia> be_PostMedia { get; set; }
        public DbSet<be_PostNotify> be_PostNotify { get; set; }
        public DbSet<be_Posts> be_Posts { get; set; }
        public DbSet<be_PostTag> be_PostTag { get; set; }
        public DbSet<be_Profiles> be_Profiles { get; set; }
        public DbSet<be_QuickNotes> be_QuickNotes { get; set; }
        public DbSet<be_QuickSettings> be_QuickSettings { get; set; }
        public DbSet<be_Referrers> be_Referrers { get; set; }
        public DbSet<be_RightRoles> be_RightRoles { get; set; }
        public DbSet<be_Rights> be_Rights { get; set; }
        public DbSet<be_Roles> be_Roles { get; set; }
        public DbSet<be_Settings> be_Settings { get; set; }
        public DbSet<be_StopWords> be_StopWords { get; set; }
        public DbSet<be_UserRoles> be_UserRoles { get; set; }
        public DbSet<be_Users> be_Users { get; set; }
        public DbSet<Bookmark> Bookmarks { get; set; }
        public DbSet<Calendar> Calendars { get; set; }
        public DbSet<CalendarShare> CalendarShares { get; set; }
        public DbSet<CategoryFeatured> CategoryFeatureds { get; set; }
        public DbSet<CategoryFeaturedHotel> CategoryFeaturedHotels { get; set; }
        public DbSet<CompanyEmployee> CompanyEmployees { get; set; }
        public DbSet<CompanyMedia> CompanyMedias { get; set; }
        public DbSet<CompanyPackage> CompanyPackages { get; set; }
        public DbSet<CompanyPackageImage> CompanyPackageImages { get; set; }
        public DbSet<CompanyPackageService> CompanyPackageServices { get; set; }
        public DbSet<Discount> Discounts { get; set; }
        public DbSet<DiscountInvite> DiscountInvites { get; set; }
        public DbSet<DiscountRegularClient> DiscountRegularClients { get; set; }
        public DbSet<DiscountService> DiscountServices { get; set; }
        public DbSet<EmployeeService> EmployeeServices { get; set; }
        public DbSet<Error> Errors { get; set; }
        public DbSet<Favorite> Favorites { get; set; }
        public DbSet<FeaturedHotel> FeaturedHotels { get; set; }
        public DbSet<GeneralTimeSlot> GeneralTimeSlots { get; set; }
        public DbSet<GettyImage> GettyImages { get; set; }
        public DbSet<GiftCard> GiftCards { get; set; }
        public DbSet<GiftCardHistory> GiftCardHistories { get; set; }
        public DbSet<GiftCardLockCust> GiftCardLockCusts { get; set; }
        public DbSet<Hotel> Hotels { get; set; }
        public DbSet<HotelCode> HotelCodes { get; set; }
        public DbSet<HotelMedia> HotelMedias { get; set; }
        public DbSet<HotelStaff> HotelStaffs { get; set; }
        public DbSet<ImageCrop> ImageCrops { get; set; }
        public DbSet<KuyamEvent> KuyamEvents { get; set; }
        public DbSet<LandingPageCompany> LandingPageCompanies { get; set; }
        public DbSet<LandingPage> LandingPages { get; set; }
        public DbSet<Medium> Media { get; set; }
        public DbSet<MediaType> MediaTypes { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<OrderGettyImageDetail> OrderGettyImageDetails { get; set; }
        public DbSet<PaymentMethod> PaymentMethods { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<ProfileCompany> ProfileCompanies { get; set; }
        public DbSet<ProfileCompanyTemp> ProfileCompanyTemps { get; set; }
        public DbSet<ProfileHour> ProfileHours { get; set; }
        public DbSet<ProfileHoursException> ProfileHoursExceptions { get; set; }
        public DbSet<ProposedAppointmentNotify> ProposedAppointmentNotifies { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<RegularClient> RegularClients { get; set; }
        public DbSet<RequestAppointment> RequestAppointments { get; set; }
        public DbSet<SeoFriendlyUrl> SeoFriendlyUrls { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<ServiceHour> ServiceHours { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<SMSMessage> SMSMessages { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Type> Types { get; set; }
        public DbSet<TypeGroup> TypeGroups { get; set; }
        public DbSet<UserBadge> UserBadges { get; set; }
        public DbSet<UserDevice> UserDevices { get; set; }
        public DbSet<UserDiscount> UserDiscounts { get; set; }
        public DbSet<UserPackagePurchase> UserPackagePurchases { get; set; }
        public DbSet<UserPackagePurchaseHistory> UserPackagePurchaseHistories { get; set; }
        public DbSet<ZipCode> ZipCodes { get; set; }
        public DbSet<FeaturedCompany> FeaturedCompanies { get; set; }
        public DbSet<Cust> Custs { get; set; }
        public DbSet<Invite> Invites { get; set; }
        public DbSet<HotelVisit> HotelVisits { get; set; }
        public DbSet<CompanyEvent> CompanyEvents { get; set; }
        public DbSet<CompanyServiceEvent> CompanyServiceEvents { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<ServiceCompany> ServiceCompanies { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<AppointmentTemp> AppointmentTemps { get; set; }
        public DbSet<NonKuyamAppointment> NonKuyamAppointments { get; set; }
        public DbSet<ProposedAppointment> ProposedAppointments { get; set; }
        public DbSet<EmployeeHour> EmployeeHours { get; set; }
        public DbSet<InstructorClassScheduler> InstructorClassSchedulers { get; set; }
        public DbSet<CompanyHour> CompanyHours { get; set; }
    }
}
