//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class LandingPage
    {
        public LandingPage()
        {
            this.LandingPageCompanies = new HashSet<LandingPageCompany>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UrlName { get; set; }
        public Nullable<int> Banner { get; set; }
        public string MainContent { get; set; }
        public int Status { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Scripts { get; set; }
    
        public virtual ImageCrop ImageCrop { get; set; }
        public virtual ICollection<LandingPageCompany> LandingPageCompanies { get; set; }
        public virtual Type Type { get; set; }
    }
    
}
