//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class LandingPageCompany
    {
        public int Id { get; set; }
        public int LandingPageId { get; set; }
        public int ProfileId { get; set; }
        public int SortOrder { get; set; }
    
        public virtual LandingPage LandingPage { get; set; }
        public virtual ProfileCompany ProfileCompany { get; set; }
    }
    
}
