//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Medium
    {
        public Medium()
        {
            this.CompanyMedias = new HashSet<CompanyMedia>();
            this.HotelMedias = new HashSet<HotelMedia>();
        }
    
        public int MediaID { get; set; }
        public int MediaTypeID { get; set; }
        public int CustID { get; set; }
        public int CustTypeID { get; set; }
        public int OwnerID { get; set; }
        public int MediaLocationTypeID { get; set; }
        public string LocationPath { get; set; }
        public string LocationData { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
    
        public virtual ICollection<CompanyMedia> CompanyMedias { get; set; }
        public virtual ICollection<HotelMedia> HotelMedias { get; set; }
    }
    
}
