//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class OrderDetail
    {
        public int OrderDetailID { get; set; }
        public string OrderDetailGuid { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> UserPackagePurchaseId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual UserPackagePurchase UserPackagePurchase { get; set; }
        public virtual Appointment Appointment { get; set; }
    }
    
}
