//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderGettyImageDetails = new HashSet<OrderGettyImageDetail>();
            this.UserDiscounts = new HashSet<UserDiscount>();
        }
    
        public int OrderID { get; set; }
        public string OrderGuID { get; set; }
        public int ProfileID { get; set; }
        public int CustID { get; set; }
        public int OrderStatusID { get; set; }
        public int PaymentStatusID { get; set; }
        public int PaymentMethodID { get; set; }
        public Nullable<decimal> OrderSubTotalDiscount { get; set; }
        public Nullable<decimal> OrderDiscount { get; set; }
        public string DiscountCodeNumber { get; set; }
        public Nullable<decimal> PercentPaymentFee { get; set; }
        public Nullable<decimal> TransactionAdditionalFee { get; set; }
        public Nullable<decimal> PaymentFeeTotal { get; set; }
        public Nullable<decimal> PercentKuyamFee { get; set; }
        public Nullable<decimal> AppointmentAdditionalFee { get; set; }
        public Nullable<decimal> KuyamFeeTotal { get; set; }
        public Nullable<decimal> OrderSubtotal { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public string CardType { get; set; }
        public string CardName { get; set; }
        public string CardNumber { get; set; }
        public string MaskedCreditCardNumber { get; set; }
        public string CardCvv2 { get; set; }
        public string CardExpirationMonth { get; set; }
        public string CardExpirationYear { get; set; }
        public string AuthorizationTransactionID { get; set; }
        public string AuthorizationTransactionCode { get; set; }
        public string AuthorizationTransactionResult { get; set; }
        public string CaptureTransactionID { get; set; }
        public string CaptureTransactionResult { get; set; }
        public string SubscriptionTransactionID { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<System.DateTime> PaidDateUtc { get; set; }
        public string TrackingNumber { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public string GiftCardCodeNumber { get; set; }
        public Nullable<decimal> GiftCardAmount { get; set; }
        public Nullable<decimal> KuyamPaidTotal { get; set; }
        public Nullable<decimal> CompanyPaidTotal { get; set; }
    
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<OrderGettyImageDetail> OrderGettyImageDetails { get; set; }
        public virtual ICollection<UserDiscount> UserDiscounts { get; set; }
        public virtual Cust Cust { get; set; }
    }
    
}
