//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class PaymentMethod
    {
        public int PaymentMethodID { get; set; }
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string PaymentAccount { get; set; }
        public int PaymentType { get; set; }
        public string ClassName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ProfileCompany ProfileCompany { get; set; }
    }
    
}
