//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class ProfileHoursException
    {
        public int ProfileHoursExceptionID { get; set; }
        public int ProfileID { get; set; }
        public bool IsOpen { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public bool AllDay { get; set; }
        public string Note { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
    
}
