//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Profile
    {
        public Profile()
        {
            this.Calendars = new HashSet<Calendar>();
            this.ProfileHours = new HashSet<ProfileHour>();
            this.ProfileHoursExceptions = new HashSet<ProfileHoursException>();
            this.FeaturedCompanies = new HashSet<FeaturedCompany>();
        }
    
        public int ProfileID { get; set; }
        public int CustID { get; set; }
        public int ProfileTypeID { get; set; }
        public int PrivacyTypeID { get; set; }
        public string Name { get; set; }
        public int RelationshipTypeID { get; set; }
        public bool IsDefault { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual ICollection<ProfileHour> ProfileHours { get; set; }
        public virtual ICollection<ProfileHoursException> ProfileHoursExceptions { get; set; }
        public virtual ICollection<FeaturedCompany> FeaturedCompanies { get; set; }
        public virtual Cust Cust { get; set; }
    }
    
}
