//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class ProfileCompanyTemp
    {
        public int ProfileID { get; set; }
        public string Name { get; set; }
        public string ContactName { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Url { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public string HoursMon { get; set; }
        public string HoursTue { get; set; }
        public string HoursWed { get; set; }
        public string HoursThur { get; set; }
        public string HoursFri { get; set; }
        public string HoursSat { get; set; }
        public string HoursSun { get; set; }
        public Nullable<int> Status { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string MonFrom { get; set; }
        public string MonTo { get; set; }
        public string TusFrom { get; set; }
        public string TusTo { get; set; }
        public string WedFrom { get; set; }
        public string WedTo { get; set; }
        public string ThurFrom { get; set; }
        public string ThurTo { get; set; }
        public string FriFrom { get; set; }
        public string FriTo { get; set; }
        public string SatFrom { get; set; }
        public string SatTo { get; set; }
        public string SunFrom { get; set; }
        public string SunTo { get; set; }
        public Nullable<bool> IsDaily { get; set; }
        public Nullable<int> CusId { get; set; }
    }
    
}
