//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class ProfileHour
    {
        public int ProfileHoursID { get; set; }
        public int ProfileID { get; set; }
        public int Day { get; set; }
        public System.TimeSpan Start { get; set; }
        public System.TimeSpan End { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
    
}
