//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class ProfileCompany
    {
        public ProfileCompany()
        {
            this.CategoryFeatureds = new HashSet<CategoryFeatured>();
            this.CompanyEmployees = new HashSet<CompanyEmployee>();
            this.CompanyMedias = new HashSet<CompanyMedia>();
            this.CompanyPackages = new HashSet<CompanyPackage>();
            this.CompanyPackageImages = new HashSet<CompanyPackageImage>();
            this.Discounts = new HashSet<Discount>();
            this.Favorites = new HashSet<Favorite>();
            this.FeaturedHotels = new HashSet<FeaturedHotel>();
            this.GeneralTimeSlots = new HashSet<GeneralTimeSlot>();
            this.GettyImages = new HashSet<GettyImage>();
            this.LandingPageCompanies = new HashSet<LandingPageCompany>();
            this.Orders = new HashSet<Order>();
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.RegularClients = new HashSet<RegularClient>();
            this.RequestAppointments = new HashSet<RequestAppointment>();
            this.FeaturedCompanies = new HashSet<FeaturedCompany>();
            this.CompanyEvents = new HashSet<CompanyEvent>();
            this.ServiceCompanies = new HashSet<ServiceCompany>();
            this.Appointments = new HashSet<Appointment>();
            this.NonKuyamAppointments = new HashSet<NonKuyamAppointment>();
            this.ProposedAppointments = new HashSet<ProposedAppointment>();
            this.CompanyHours = new HashSet<CompanyHour>();
        }
    
        public int ProfileID { get; set; }
        public int CompanyTypeID { get; set; }
        public int CompanyStatusID { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Url { get; set; }
        public string YoutubeLink { get; set; }
        public Nullable<int> PreferredContact { get; set; }
        public Nullable<int> FirstAlert { get; set; }
        public Nullable<int> SecondAlert { get; set; }
        public string PaymentOptions { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<int> PayAfter { get; set; }
        public string MapUrl { get; set; }
        public string Neighborhood { get; set; }
        public string CrossStreet { get; set; }
        public string PublicTransportation { get; set; }
        public string Parking { get; set; }
        public string Notes { get; set; }
        public bool ApptAutoConfirm { get; set; }
        public int ApptDefaultSlotDuration { get; set; }
        public int ApptDefaultPeoplePerSlot { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public Nullable<int> CancelPolicy { get; set; }
        public Nullable<int> CancelHour { get; set; }
        public Nullable<int> CancelRefundPercent { get; set; }
        public string MobileCarrier { get; set; }
        public Nullable<bool> IsShowCatagory { get; set; }
        public Nullable<bool> IsEvent { get; set; }
        public Nullable<bool> IsClass { get; set; }
    
        public virtual ICollection<CategoryFeatured> CategoryFeatureds { get; set; }
        public virtual ICollection<CompanyEmployee> CompanyEmployees { get; set; }
        public virtual ICollection<CompanyMedia> CompanyMedias { get; set; }
        public virtual ICollection<CompanyPackage> CompanyPackages { get; set; }
        public virtual ICollection<CompanyPackageImage> CompanyPackageImages { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<FeaturedHotel> FeaturedHotels { get; set; }
        public virtual ICollection<GeneralTimeSlot> GeneralTimeSlots { get; set; }
        public virtual ICollection<GettyImage> GettyImages { get; set; }
        public virtual ICollection<LandingPageCompany> LandingPageCompanies { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual ICollection<RegularClient> RegularClients { get; set; }
        public virtual ICollection<RequestAppointment> RequestAppointments { get; set; }
        public virtual ICollection<FeaturedCompany> FeaturedCompanies { get; set; }
        public virtual ICollection<CompanyEvent> CompanyEvents { get; set; }
        public virtual ICollection<ServiceCompany> ServiceCompanies { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<NonKuyamAppointment> NonKuyamAppointments { get; set; }
        public virtual ICollection<ProposedAppointment> ProposedAppointments { get; set; }
        public virtual ICollection<CompanyHour> CompanyHours { get; set; }
    }
    
}
