//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class ProposedAppointment
    {
        public ProposedAppointment()
        {
            this.ProposedAppointmentNotifies = new HashSet<ProposedAppointmentNotify>();
        }
    
        public int AppointmentID { get; set; }
        public Nullable<int> ServiceCompanyId { get; set; }
        public int AppointmentStatusID { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public string Description { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Notes { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int CustID { get; set; }
        public Nullable<int> CalendarId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> AttendeesNumber { get; set; }
        public int ProfileId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string ServiceName { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Cust Cust { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual HotelStaff HotelStaff { get; set; }
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceCompany ServiceCompany { get; set; }
        public virtual ICollection<ProposedAppointmentNotify> ProposedAppointmentNotifies { get; set; }
    }
    
}
