//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Rating
    {
        public int ID { get; set; }
        public int CustID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int ServiceCompanyID { get; set; }
        public string Content { get; set; }
        public Nullable<int> RatingValue { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public string PrivateContent { get; set; }
    
        public virtual CompanyEmployee CompanyEmployee { get; set; }
        public virtual Cust Cust { get; set; }
        public virtual ServiceCompany ServiceCompany { get; set; }
    }
    
}
