//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class RegularClient
    {
        public RegularClient()
        {
            this.DiscountRegularClients = new HashSet<DiscountRegularClient>();
        }
    
        public int RegularClientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CompanyProfileId { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<DiscountRegularClient> DiscountRegularClients { get; set; }
        public virtual ProfileCompany ProfileCompany { get; set; }
    }
    
}
