//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class ServiceHour
    {
        public int ServiceHoursID { get; set; }
        public System.TimeSpan FromHour { get; set; }
        public System.TimeSpan ToHour { get; set; }
        public int ServiceCompanyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string DayOfWeek { get; set; }
    
        public virtual ServiceCompany ServiceCompany { get; set; }
    }
    
}
