//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Service
    {
        public Service()
        {
            this.Service1 = new HashSet<Service>();
            this.ServiceCompanies = new HashSet<ServiceCompany>();
            this.NonKuyamAppointments = new HashSet<NonKuyamAppointment>();
            this.ProposedAppointments = new HashSet<ProposedAppointment>();
        }
    
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string Desc { get; set; }
        public Nullable<int> ParentServiceID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> Status { get; set; }
        public string kalturaId { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        public virtual ICollection<Service> Service1 { get; set; }
        public virtual Service Service2 { get; set; }
        public virtual ICollection<ServiceCompany> ServiceCompanies { get; set; }
        public virtual ICollection<NonKuyamAppointment> NonKuyamAppointments { get; set; }
        public virtual ICollection<ProposedAppointment> ProposedAppointments { get; set; }
    }
    
}
