//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class ServiceCompany
    {
        public ServiceCompany()
        {
            this.CompanyPackageServices = new HashSet<CompanyPackageService>();
            this.CompanyServiceEvents = new HashSet<CompanyServiceEvent>();
            this.DiscountServices = new HashSet<DiscountService>();
            this.EmployeeServices = new HashSet<EmployeeService>();
            this.Ratings = new HashSet<Rating>();
            this.RequestAppointments = new HashSet<RequestAppointment>();
            this.ServiceHours = new HashSet<ServiceHour>();
            this.Appointments = new HashSet<Appointment>();
            this.ProposedAppointments = new HashSet<ProposedAppointment>();
        }
    
        public int ServiceCompanyID { get; set; }
        public int ProfileID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> FromDateTime { get; set; }
        public Nullable<System.DateTime> ToDateTime { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> AttendeesNumber { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public string ServiceName { get; set; }
        public string EmployeeName { get; set; }
        public int ServiceTypeId { get; set; }
        public bool IsPerDay { get; set; }
    
        public virtual ICollection<CompanyPackageService> CompanyPackageServices { get; set; }
        public virtual ICollection<CompanyServiceEvent> CompanyServiceEvents { get; set; }
        public virtual ICollection<DiscountService> DiscountServices { get; set; }
        public virtual ICollection<EmployeeService> EmployeeServices { get; set; }
        public virtual ProfileCompany ProfileCompany { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<RequestAppointment> RequestAppointments { get; set; }
        public virtual Service Service { get; set; }
        public virtual ICollection<ServiceHour> ServiceHours { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<ProposedAppointment> ProposedAppointments { get; set; }
    }
    
}
