//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Setting
    {
        public string Name { get; set; }
        public string Value { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
    
}
