//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class SMSMessage
    {
        public int Id { get; set; }
        public string MessageId { get; set; }
        public Nullable<int> CustId { get; set; }
        public string Message { get; set; }
        public string SenderAddress { get; set; }
        public string DestinationAddress { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public string ErrorCode { get; set; }
        public string DecriptionStatus { get; set; }
        public int ReceivedStatus { get; set; }
    }
    
}
