//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class Type
    {
        public Type()
        {
            this.LandingPages = new HashSet<LandingPage>();
        }
    
        public int TypeID { get; set; }
        public int TypeGroupID { get; set; }
        public int Sequence { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentTypeID { get; set; }
        public string Data { get; set; }
        public int OverrideID { get; set; }
    
        public virtual ICollection<LandingPage> LandingPages { get; set; }
    }
    
}
