//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class UserDevice
    {
        public int UserDeviceId { get; set; }
        public int CustId { get; set; }
        public string DeviceID { get; set; }
        public int DeviceType { get; set; }
        public System.DateTime DateUsage { get; set; }
        public int AppId { get; set; }
        public int ServiceVersion { get; set; }
    }
    
}
