//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class UserPackagePurchaseHistory
    {
        public int UserPackagePurchaseHistoryId { get; set; }
        public int UserPackagePurchaseId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int AppointmentID { get; set; }
    
        public virtual UserPackagePurchase UserPackagePurchase { get; set; }
        public virtual Appointment Appointment { get; set; }
    }
    
}
