//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class UserPackagePurchase
    {
        public UserPackagePurchase()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.UserPackagePurchaseHistories = new HashSet<UserPackagePurchaseHistory>();
        }
    
        public int UserPackagePurchaseId { get; set; }
        public int CompanyPackageId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int MaxUses { get; set; }
        public decimal OrginalPrice { get; set; }
        public decimal PurchasePrice { get; set; }
        public int CustID { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<int> UserPackageStatus { get; set; }
    
        public virtual CompanyPackage CompanyPackage { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<UserPackagePurchaseHistory> UserPackagePurchaseHistories { get; set; }
    }
    
}
