//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class UserBadge
    {
        public int UserBadgeId { get; set; }
        public int CustID { get; set; }
        public int BadgeUnread { get; set; }
        public int TotalSent { get; set; }
    
        public virtual Cust Cust { get; set; }
    }
    
}
