//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kuyam.Database
{
    public partial class ZipCode
    {
        public int ZipCodeId { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public bool Active { get; set; }
        public string State { get; set; }
    }
    
}
