//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuyam.WebUI.InfoConnServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kuyam.com/", ConfigurationName="InfoConnServiceReference.InfoConnSoap")]
    public interface InfoConnSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/ExportEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        bool ExportEvents(Kuyam.WebUI.InfoConnServiceReference.Event[] events, string filepath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/ExportEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ExportEventsAsync(Kuyam.WebUI.InfoConnServiceReference.Event[] events, string filepath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/SaveEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        bool SaveEvents(int userId, Kuyam.WebUI.InfoConnServiceReference.SearchOption searchInfo, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/SaveEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SaveEventsAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.SearchOption searchInfo, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.Event[] GetEvents(int userId, Kuyam.WebUI.InfoConnServiceReference.SearchOption searchInfo, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Event[]> GetEventsAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.SearchOption searchInfo, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.Event GetEvent(int userId, string eventId, string calendarId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Event> GetEventAsync(int userId, string eventId, string calendarId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetRangeEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.Event[] GetRangeEvent(int userId, System.DateTime startDate, System.DateTime endDate, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetRangeEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Event[]> GetRangeEventAsync(int userId, System.DateTime startDate, System.DateTime endDate, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/PostEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        string PostEvent(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType connectorSourceType, Kuyam.WebUI.InfoConnServiceReference.Event postEventPara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/PostEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PostEventAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType connectorSourceType, Kuyam.WebUI.InfoConnServiceReference.Event postEventPara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/DeleteEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        bool DeleteEvent(int userId, string eventId, string calendarId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/DeleteEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteEventAsync(int userId, string eventId, string calendarId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetCalendars", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.Calendar[] GetCalendars(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetCalendars", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Calendar[]> GetCalendarsAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetCalendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.Calendar GetCalendar(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType, string calendarId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetCalendar", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Calendar> GetCalendarAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType, string calendarId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/AddConnectorSource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.Calendar[] AddConnectorSource(Kuyam.WebUI.InfoConnServiceReference.ConnectorSource connectorSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/AddConnectorSource", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Calendar[]> AddConnectorSourceAsync(Kuyam.WebUI.InfoConnServiceReference.ConnectorSource connectorSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetConnectorSource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.ConnectorSource GetConnectorSource(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType connectorSourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetConnectorSource", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.ConnectorSource> GetConnectorSourceAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType connectorSourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/AddIncomingRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean AddIncomingRequest(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest, Kuyam.WebUI.InfoConnServiceReference.IncommingRequestType requestType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/AddIncomingRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean> AddIncomingRequestAsync(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest, Kuyam.WebUI.InfoConnServiceReference.IncommingRequestType requestType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/UpdateUserSetting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean UpdateUserSetting(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/UpdateUserSetting", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean> UpdateUserSettingAsync(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/UpdateAppointment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean UpdateAppointment(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/UpdateAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean> UpdateAppointmentAsync(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/RefreshUserCalendars", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        bool RefreshUserCalendars(int userId, Kuyam.WebUI.InfoConnServiceReference.CacheType cacheHorizon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/RefreshUserCalendars", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RefreshUserCalendarsAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.CacheType cacheHorizon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/RefreshUserCalendarsAllCaches", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        bool RefreshUserCalendarsAllCaches(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/RefreshUserCalendarsAllCaches", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RefreshUserCalendarsAllCachesAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetBusyInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        Kuyam.WebUI.InfoConnServiceReference.BusyInfo[] GetBusyInfo(Kuyam.WebUI.InfoConnServiceReference.SearchOption searchOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetBusyInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.BusyInfo[]> GetBusyInfoAsync(Kuyam.WebUI.InfoConnServiceReference.SearchOption searchOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetExternalFeed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        string GetExternalFeed(Kuyam.WebUI.InfoConnServiceReference.Event[] events);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kuyam.com/GetExternalFeed", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetExternalFeedAsync(Kuyam.WebUI.InfoConnServiceReference.Event[] events);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public partial class Event : BaseEntity {
        
        private string eventIdField;
        
        private int connectorSourceIdField;
        
        private System.Nullable<int> calendarIdField;
        
        private string summaryField;
        
        private string descriptionField;
        
        private string locationField;
        
        private string uIdField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EventId {
            get {
                return this.eventIdField;
            }
            set {
                this.eventIdField = value;
                this.RaisePropertyChanged("EventId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ConnectorSourceId {
            get {
                return this.connectorSourceIdField;
            }
            set {
                this.connectorSourceIdField = value;
                this.RaisePropertyChanged("ConnectorSourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> CalendarId {
            get {
                return this.calendarIdField;
            }
            set {
                this.calendarIdField = value;
                this.RaisePropertyChanged("CalendarId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("Summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UId {
            get {
                return this.uIdField;
            }
            set {
                this.uIdField = value;
                this.RaisePropertyChanged("UId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IncomingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConnectorSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Calendar))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Event))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public abstract partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public partial class BusyInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private ConnectorSourceType sourceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ConnectorSourceType SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
                this.RaisePropertyChanged("SourceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public enum ConnectorSourceType {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Google,
        
        /// <remarks/>
        Facebook,
        
        /// <remarks/>
        iCalendar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public partial class ServiceErrorOfBoolean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public partial class ServiceResponseOfBoolean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isSuccessField;
        
        private bool responseField;
        
        private ServiceErrorOfBoolean errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
                this.RaisePropertyChanged("IsSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ServiceErrorOfBoolean Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Stream))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public abstract partial class Stream : MarshalByRefObject {
        
        private long positionField;
        
        private int readTimeoutField;
        
        private int writeTimeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ReadTimeout {
            get {
                return this.readTimeoutField;
            }
            set {
                this.readTimeoutField = value;
                this.RaisePropertyChanged("ReadTimeout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int WriteTimeout {
            get {
                return this.writeTimeoutField;
            }
            set {
                this.writeTimeoutField = value;
                this.RaisePropertyChanged("WriteTimeout");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public partial class SearchOption : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConnectorSourceType connectorSourceField;
        
        private string iCSStringField;
        
        private string iCSFilePathField;
        
        private string eventIdField;
        
        private Stream iCSStreamField;
        
        private object ownerField;
        
        private string nameField;
        
        private string descriptionField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private string locationField;
        
        private object venueField;
        
        private string privacyField;
        
        private System.DateTime updateDateField;
        
        private string rSVStatusField;
        
        private int uIdField;
        
        private string calendarIdField;
        
        private ConnectorSourceType connectorSourceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConnectorSourceType ConnectorSource {
            get {
                return this.connectorSourceField;
            }
            set {
                this.connectorSourceField = value;
                this.RaisePropertyChanged("ConnectorSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ICSString {
            get {
                return this.iCSStringField;
            }
            set {
                this.iCSStringField = value;
                this.RaisePropertyChanged("ICSString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ICSFilePath {
            get {
                return this.iCSFilePathField;
            }
            set {
                this.iCSFilePathField = value;
                this.RaisePropertyChanged("ICSFilePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EventId {
            get {
                return this.eventIdField;
            }
            set {
                this.eventIdField = value;
                this.RaisePropertyChanged("EventId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Stream ICSStream {
            get {
                return this.iCSStreamField;
            }
            set {
                this.iCSStreamField = value;
                this.RaisePropertyChanged("ICSStream");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public object Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public object Venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
                this.RaisePropertyChanged("Venue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Privacy {
            get {
                return this.privacyField;
            }
            set {
                this.privacyField = value;
                this.RaisePropertyChanged("Privacy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
                this.RaisePropertyChanged("UpdateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string RSVStatus {
            get {
                return this.rSVStatusField;
            }
            set {
                this.rSVStatusField = value;
                this.RaisePropertyChanged("RSVStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int UId {
            get {
                return this.uIdField;
            }
            set {
                this.uIdField = value;
                this.RaisePropertyChanged("UId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CalendarId {
            get {
                return this.calendarIdField;
            }
            set {
                this.calendarIdField = value;
                this.RaisePropertyChanged("CalendarId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public ConnectorSourceType ConnectorSourceType {
            get {
                return this.connectorSourceTypeField;
            }
            set {
                this.connectorSourceTypeField = value;
                this.RaisePropertyChanged("ConnectorSourceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public partial class IncomingRequest : BaseEntity {
        
        private string guiIdField;
        
        private string entityIdField;
        
        private System.Nullable<int> entityTypeField;
        
        private int requestTypeField;
        
        private int statusField;
        
        private string decriptionField;
        
        private System.DateTime createdDateField;
        
        private System.DateTime lastRequestedDateField;
        
        private int retryField;
        
        private int maxRetryField;
        
        private System.DateTime lastRetryDateField;
        
        private System.Nullable<int> custIdField;
        
        private System.Nullable<int> previousAlertField;
        
        private System.Nullable<System.DateTime> dateAlertField;
        
        private System.Nullable<int> appointmentIdField;
        
        private System.Nullable<System.DateTime> apptStartDateField;
        
        private string dataField;
        
        private int priorityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GuiId {
            get {
                return this.guiIdField;
            }
            set {
                this.guiIdField = value;
                this.RaisePropertyChanged("GuiId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
                this.RaisePropertyChanged("EntityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> EntityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
                this.RaisePropertyChanged("EntityType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Decription {
            get {
                return this.decriptionField;
            }
            set {
                this.decriptionField = value;
                this.RaisePropertyChanged("Decription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime LastRequestedDate {
            get {
                return this.lastRequestedDateField;
            }
            set {
                this.lastRequestedDateField = value;
                this.RaisePropertyChanged("LastRequestedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Retry {
            get {
                return this.retryField;
            }
            set {
                this.retryField = value;
                this.RaisePropertyChanged("Retry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int MaxRetry {
            get {
                return this.maxRetryField;
            }
            set {
                this.maxRetryField = value;
                this.RaisePropertyChanged("MaxRetry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime LastRetryDate {
            get {
                return this.lastRetryDateField;
            }
            set {
                this.lastRetryDateField = value;
                this.RaisePropertyChanged("LastRetryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> CustId {
            get {
                return this.custIdField;
            }
            set {
                this.custIdField = value;
                this.RaisePropertyChanged("CustId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> PreviousAlert {
            get {
                return this.previousAlertField;
            }
            set {
                this.previousAlertField = value;
                this.RaisePropertyChanged("PreviousAlert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> DateAlert {
            get {
                return this.dateAlertField;
            }
            set {
                this.dateAlertField = value;
                this.RaisePropertyChanged("DateAlert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> AppointmentId {
            get {
                return this.appointmentIdField;
            }
            set {
                this.appointmentIdField = value;
                this.RaisePropertyChanged("AppointmentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> ApptStartDate {
            get {
                return this.apptStartDateField;
            }
            set {
                this.apptStartDateField = value;
                this.RaisePropertyChanged("ApptStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public partial class ConnectorSource : BaseEntity {
        
        private int userIdField;
        
        private int connectorSourceTypeField;
        
        private string feedUrlField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string accessTokenField;
        
        private string refressTokenField;
        
        private System.DateTime lastModifiedField;
        
        private System.DateTime expiresDateField;
        
        private bool isUpdateRunningField;
        
        private Event[] eventsField;
        
        private System.DateTime cacheLastUpdate_ShortField;
        
        private System.DateTime cacheLastUpdate_MediumField;
        
        private System.DateTime cacheLastUpdate_LongerField;
        
        private bool doCacheUpdate_ShortField;
        
        private bool doCacheUpdate_MediumField;
        
        private bool doCacheUpdate_LongerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ConnectorSourceType {
            get {
                return this.connectorSourceTypeField;
            }
            set {
                this.connectorSourceTypeField = value;
                this.RaisePropertyChanged("ConnectorSourceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FeedUrl {
            get {
                return this.feedUrlField;
            }
            set {
                this.feedUrlField = value;
                this.RaisePropertyChanged("FeedUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AccessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("AccessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RefressToken {
            get {
                return this.refressTokenField;
            }
            set {
                this.refressTokenField = value;
                this.RaisePropertyChanged("RefressToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime LastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("LastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime ExpiresDate {
            get {
                return this.expiresDateField;
            }
            set {
                this.expiresDateField = value;
                this.RaisePropertyChanged("ExpiresDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsUpdateRunning {
            get {
                return this.isUpdateRunningField;
            }
            set {
                this.isUpdateRunningField = value;
                this.RaisePropertyChanged("IsUpdateRunning");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public Event[] Events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
                this.RaisePropertyChanged("Events");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime CacheLastUpdate_Short {
            get {
                return this.cacheLastUpdate_ShortField;
            }
            set {
                this.cacheLastUpdate_ShortField = value;
                this.RaisePropertyChanged("CacheLastUpdate_Short");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime CacheLastUpdate_Medium {
            get {
                return this.cacheLastUpdate_MediumField;
            }
            set {
                this.cacheLastUpdate_MediumField = value;
                this.RaisePropertyChanged("CacheLastUpdate_Medium");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime CacheLastUpdate_Longer {
            get {
                return this.cacheLastUpdate_LongerField;
            }
            set {
                this.cacheLastUpdate_LongerField = value;
                this.RaisePropertyChanged("CacheLastUpdate_Longer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool DoCacheUpdate_Short {
            get {
                return this.doCacheUpdate_ShortField;
            }
            set {
                this.doCacheUpdate_ShortField = value;
                this.RaisePropertyChanged("DoCacheUpdate_Short");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool DoCacheUpdate_Medium {
            get {
                return this.doCacheUpdate_MediumField;
            }
            set {
                this.doCacheUpdate_MediumField = value;
                this.RaisePropertyChanged("DoCacheUpdate_Medium");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool DoCacheUpdate_Longer {
            get {
                return this.doCacheUpdate_LongerField;
            }
            set {
                this.doCacheUpdate_LongerField = value;
                this.RaisePropertyChanged("DoCacheUpdate_Longer");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public partial class Calendar : BaseEntity {
        
        private string calendarIdField;
        
        private int connectorSourceIdField;
        
        private string summaryField;
        
        private string descriptionField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CalendarId {
            get {
                return this.calendarIdField;
            }
            set {
                this.calendarIdField = value;
                this.RaisePropertyChanged("CalendarId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ConnectorSourceId {
            get {
                return this.connectorSourceIdField;
            }
            set {
                this.connectorSourceIdField = value;
                this.RaisePropertyChanged("ConnectorSourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("Summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public enum IncommingRequestType {
        
        /// <remarks/>
        SEND_EMAIL,
        
        /// <remarks/>
        SEND_SMS,
        
        /// <remarks/>
        PAYMENT_PAYPAL,
        
        /// <remarks/>
        PAYMENT_AMAZON,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kuyam.com/")]
    public enum CacheType {
        
        /// <remarks/>
        Short,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Longer,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InfoConnSoapChannel : Kuyam.WebUI.InfoConnServiceReference.InfoConnSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InfoConnSoapClient : System.ServiceModel.ClientBase<Kuyam.WebUI.InfoConnServiceReference.InfoConnSoap>, Kuyam.WebUI.InfoConnServiceReference.InfoConnSoap {
        
        public InfoConnSoapClient() {
        }
        
        public InfoConnSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InfoConnSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoConnSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoConnSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ExportEvents(Kuyam.WebUI.InfoConnServiceReference.Event[] events, string filepath) {
            return base.Channel.ExportEvents(events, filepath);
        }
        
        public System.Threading.Tasks.Task<bool> ExportEventsAsync(Kuyam.WebUI.InfoConnServiceReference.Event[] events, string filepath) {
            return base.Channel.ExportEventsAsync(events, filepath);
        }
        
        public bool SaveEvents(int userId, Kuyam.WebUI.InfoConnServiceReference.SearchOption searchInfo, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.SaveEvents(userId, searchInfo, sourceType);
        }
        
        public System.Threading.Tasks.Task<bool> SaveEventsAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.SearchOption searchInfo, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.SaveEventsAsync(userId, searchInfo, sourceType);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.Event[] GetEvents(int userId, Kuyam.WebUI.InfoConnServiceReference.SearchOption searchInfo, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.GetEvents(userId, searchInfo, sourceType);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Event[]> GetEventsAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.SearchOption searchInfo, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.GetEventsAsync(userId, searchInfo, sourceType);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.Event GetEvent(int userId, string eventId, string calendarId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.GetEvent(userId, eventId, calendarId, sourceType);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Event> GetEventAsync(int userId, string eventId, string calendarId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.GetEventAsync(userId, eventId, calendarId, sourceType);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.Event[] GetRangeEvent(int userId, System.DateTime startDate, System.DateTime endDate, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.GetRangeEvent(userId, startDate, endDate, sourceType);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Event[]> GetRangeEventAsync(int userId, System.DateTime startDate, System.DateTime endDate, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.GetRangeEventAsync(userId, startDate, endDate, sourceType);
        }
        
        public string PostEvent(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType connectorSourceType, Kuyam.WebUI.InfoConnServiceReference.Event postEventPara) {
            return base.Channel.PostEvent(userId, connectorSourceType, postEventPara);
        }
        
        public System.Threading.Tasks.Task<string> PostEventAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType connectorSourceType, Kuyam.WebUI.InfoConnServiceReference.Event postEventPara) {
            return base.Channel.PostEventAsync(userId, connectorSourceType, postEventPara);
        }
        
        public bool DeleteEvent(int userId, string eventId, string calendarId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.DeleteEvent(userId, eventId, calendarId, sourceType);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEventAsync(int userId, string eventId, string calendarId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.DeleteEventAsync(userId, eventId, calendarId, sourceType);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.Calendar[] GetCalendars(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.GetCalendars(userId, sourceType);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Calendar[]> GetCalendarsAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType) {
            return base.Channel.GetCalendarsAsync(userId, sourceType);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.Calendar GetCalendar(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType, string calendarId) {
            return base.Channel.GetCalendar(userId, sourceType, calendarId);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Calendar> GetCalendarAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType sourceType, string calendarId) {
            return base.Channel.GetCalendarAsync(userId, sourceType, calendarId);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.Calendar[] AddConnectorSource(Kuyam.WebUI.InfoConnServiceReference.ConnectorSource connectorSource) {
            return base.Channel.AddConnectorSource(connectorSource);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.Calendar[]> AddConnectorSourceAsync(Kuyam.WebUI.InfoConnServiceReference.ConnectorSource connectorSource) {
            return base.Channel.AddConnectorSourceAsync(connectorSource);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.ConnectorSource GetConnectorSource(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType connectorSourceType) {
            return base.Channel.GetConnectorSource(userId, connectorSourceType);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.ConnectorSource> GetConnectorSourceAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.ConnectorSourceType connectorSourceType) {
            return base.Channel.GetConnectorSourceAsync(userId, connectorSourceType);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean AddIncomingRequest(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest, Kuyam.WebUI.InfoConnServiceReference.IncommingRequestType requestType) {
            return base.Channel.AddIncomingRequest(incomingRequest, requestType);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean> AddIncomingRequestAsync(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest, Kuyam.WebUI.InfoConnServiceReference.IncommingRequestType requestType) {
            return base.Channel.AddIncomingRequestAsync(incomingRequest, requestType);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean UpdateUserSetting(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest) {
            return base.Channel.UpdateUserSetting(incomingRequest);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean> UpdateUserSettingAsync(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest) {
            return base.Channel.UpdateUserSettingAsync(incomingRequest);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean UpdateAppointment(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest) {
            return base.Channel.UpdateAppointment(incomingRequest);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.ServiceResponseOfBoolean> UpdateAppointmentAsync(Kuyam.WebUI.InfoConnServiceReference.IncomingRequest incomingRequest) {
            return base.Channel.UpdateAppointmentAsync(incomingRequest);
        }
        
        public bool RefreshUserCalendars(int userId, Kuyam.WebUI.InfoConnServiceReference.CacheType cacheHorizon) {
            return base.Channel.RefreshUserCalendars(userId, cacheHorizon);
        }
        
        public System.Threading.Tasks.Task<bool> RefreshUserCalendarsAsync(int userId, Kuyam.WebUI.InfoConnServiceReference.CacheType cacheHorizon) {
            return base.Channel.RefreshUserCalendarsAsync(userId, cacheHorizon);
        }
        
        public bool RefreshUserCalendarsAllCaches(int userId) {
            return base.Channel.RefreshUserCalendarsAllCaches(userId);
        }
        
        public System.Threading.Tasks.Task<bool> RefreshUserCalendarsAllCachesAsync(int userId) {
            return base.Channel.RefreshUserCalendarsAllCachesAsync(userId);
        }
        
        public Kuyam.WebUI.InfoConnServiceReference.BusyInfo[] GetBusyInfo(Kuyam.WebUI.InfoConnServiceReference.SearchOption searchOption) {
            return base.Channel.GetBusyInfo(searchOption);
        }
        
        public System.Threading.Tasks.Task<Kuyam.WebUI.InfoConnServiceReference.BusyInfo[]> GetBusyInfoAsync(Kuyam.WebUI.InfoConnServiceReference.SearchOption searchOption) {
            return base.Channel.GetBusyInfoAsync(searchOption);
        }
        
        public string GetExternalFeed(Kuyam.WebUI.InfoConnServiceReference.Event[] events) {
            return base.Channel.GetExternalFeed(events);
        }
        
        public System.Threading.Tasks.Task<string> GetExternalFeedAsync(Kuyam.WebUI.InfoConnServiceReference.Event[] events) {
            return base.Channel.GetExternalFeedAsync(events);
        }
    }
}
